

import { Inter } from "next/font/google";
import Header from "app/components/shared/Header/Header";
import { Footer } from "app/components/shared/Footer";
import  "app/sass/globals.sass"
const inter = Inter({ subsets: ["latin"] });


// export const metadata: Metadata = {
//   title: "Future world",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Header/>
        {children}
        
        </body>
    </html>
  );
}
